package e

import (
	"errors"
)

var (
	ErrKeyNotExists        = errors.New("key of map is not exists")
	ErrEmpty               = errors.New("empty slice or array")
	ErrOutOfRange          = errors.New("index out of range")
	ErrExists              = errors.New("target exists")
	ErrNotExists           = errors.New("target not exists")
	ErrConfig              = errors.New("config file error")
	ErrUnsupported         = errors.New("functions or parameters unsupported")
	ErrClosed              = errors.New("handle have been closed")
	ErrCantConnect         = errors.New("can not connect to destination")
	ErrImplemented         = errors.New("have not implemented")
	ErrInterface           = errors.New("unsupported interface")
	ErrParams              = errors.New("bad parameters")
	ErrLength              = errors.New("invalid length")
	ErrNotEqual            = errors.New("values not equal")
	ErrInsufficientBalance = errors.New("insufficient balance")
	ErrTimeout             = errors.New("timeout")
	ErrExpired             = errors.New("expired")
	ErrTooFrequently       = errors.New("operation too frequently")
	ErrOccupied            = errors.New("resource has been occupied")
	ErrDup                 = errors.New("duplicate operations")
	ErrUnbind              = errors.New("have not bind")
	ErrFormat              = errors.New("invalid format")
	ErrNoReaction          = errors.New("target not reaction")
	ErrParsing             = errors.New("parse error")
	ErrVersion             = errors.New("version mismatch")
	ErrOnline              = errors.New("target online")
	ErrOffline             = errors.New("target offline")
	ErrAuth                = errors.New("Auth failed")
	ErrNeedPreAuth         = errors.New("pre-auth is needed")
	ErrFailed              = errors.New("operation failed")
	ErrPending             = errors.New("pending")
	ErrMaintaining         = errors.New("service is maintaining")
	ErrUnknown             = errors.New("unknown error")
	ErrOK                  = errors.New("no error")
)
